config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get 'comments/index'
  get 'comments/new'
  
  devise_for :users
  resources :posts do
    resources :comments
  end
  resources :places do
    resources :comments
  end

  resources :users
  resources :orders

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/place.rb
class Place < ApplicationRecord
  validates :description, presence: true, length: { maximum: 1000 }
  validates :title, presence: true, length: { maximum: 50 }
  validates :address, presence: true, length: { maximum: 150 }  

  has_many :comments, as: :commentable
  belongs_to :user

  #generates longitude and latitude from address data
  geocoded_by :address
  after_validation :geocode  
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!
  #before_action :set_place, only: [:show, :edit, :update, :destroy]

  def index
    @places = Place.order("title")
    @hash = Gmaps4rails.build_markers(@places) do |place, marker|
      marker.lat place.latitude
      marker.lng place.longitude
      marker.infowindow place.title
    end
  end

  def show
    @users = User.all
    @place = Place.find(params[:id])
    @commentable = @place
    @comments = @commentable.comments
    @comment = Comment.new
  end

  def new
    @user = current_user
    @place = @user.places.new
  end

  def edit
    @place = Place.find(params[:id])
    if @place.user_id != current_user.id
      redirect_to places_url
    end
  end

  def create
    @user = current_user
    @place = @user.places.new(place_params)
      respond_to do |format|  
        if @place.save
          format.html { redirect_to @place, notice: 'Place was successfully created.' }
          format.json { render :show, status: :created, location: @place }
        else
          format.html { render :new }
          format.json { render json: @place.errors, status: :unprocessable_entity }
        end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    @user = current_user    
      respond_to do |format|
        if @user.places.update(place_params)
          format.html { redirect_to :place, notice: 'Place was successfully updated.' }
          format.json { render :show, status: :ok, location: @place }
        else
          format.html { render :edit }
          format.json { render json: @place.errors, status: :unprocessable_entity }
        end
      end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place = Place.find(params[:id])
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:description, :title, :tags, :address, :latitude, :longitude, :espresso, :cappuccino, :latte )
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_with(model: place, local: true) do |form| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>
      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :place_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :place_description %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :place_address %>
  </div>

  <div class="field">
    <%= form.label :tags %>
    <%= form.text_field :tags, id: :place_tags %>
  </div>
  
  <div class="field">
    <table>
      <tr>
        <td>
          <%= form.label :espresso %>
          <%= form.check_box :espresso %>
        </td>
        <td>
          <%= form.label :cappuccino %>
          <%= form.check_box :cappuccino %>
        </td>
        <td>
          <%= form.label :latte %>
          <%= form.check_box :latte %>
        </td>
      </tr>
    </table>
  </div>

  <div class="actions">
    <%= form.submit 'Settle place', :class => 'btn-1'  %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('places.places') %></h1>

<!-- Defalut button method (POST) changed to GET -->
<p><%= button_to 'New Place', new_place_path, :class => 'btn-1', :method => :get %></p>

<table class="table">
  <theader>
    <th>Title:</th>
    <th>We serve:</th>
    <th>Address:</th>
    <th>Description:</th> 
    <th></th> 
  </theader>
  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><strong><%= link_to "#{place.title}", place %></strong></td>        
        <td><%if place.espresso == true%>// ESPRESSO <% end %> <%if place.cappuccino == true%>// CAPPUCCINO <% end %> <%if place.latte == true%>// LATTE <% end %></td>
        <td><%= place.address %></td>
        <td><%= link_to "#{place.description[0..25]}...", place %></td>
        <td><% if current_user.id == place.user_id %> | <%= link_to 'Edit', edit_place_path(place) %> | <%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %><%end%></td>
      </tr>
    <% end %>
  </tbody>
</table> 
<br>  

<!-- Google map frame -->
<div style='width: 100%;'>
  <div id="map" style='width: 100%; height: 400px;'></div>
</div>

<!-- Gmap javascript -->
<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });

</script>

app/views/places/new.html.erb
<h1>New Place</h1>

<h3><%= link_to 'Back', places_path %></h3>

<%= render 'form', place: @place %>

app/views/places/show.html.erb
<h1><%= @place.title %></h1>

<p id="notice"><%= notice %></p>

<h3><%= link_to 'Back to places', places_path %></h3>

<!-- Javascript function buttons - adds 1 item order to cart -->
<p>
<strong>Order coffee: </strong>
<%if @place.espresso == true %><button class="btn btn-4" onclick='coffee_function("<%= @place.title + '_espresso' %>")'> +1 espresso </button><% end %>
<%if @place.cappuccino == true %><button class="btn btn-4" onclick='coffee_function("<%= @place.title + '_cappuccino' %>")'> +1 cappuccino </button><% end %>
<%if @place.latte == true %><button class="btn btn-4" onclick='coffee_function("<%= @place.title + '_latte' %>")'> +1 latte </button><% end %>
</p>

<p>
  <strong>Description:</strong>
  <%= @place.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @place.address %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @place.tags %>
</p>

<i> registered by <%= @users.find(@place.user_id).username %> </i>

<!-- 'edit button is visible only for place creator' --> 
<p><% if current_user.id == @place.user_id %><%= link_to 'Edit', edit_place_path(@place) %><% end %></p>

<%= render "comments/comments" %>
<%= render "comments/form" %>


<script type="text/javascript">

// Function places order data to Local Storage.
// After that data is being copied to <input type="hidden" name="orders_btn" id="orders_input" > at application.html.erb 
// Function takes localStorage item value by it's key, increases value by '1', sets new value to key in localStorage ( updates key-value pair)  
function coffee_function(variable) 
{ 
	alert ('Dear Adept, you have added 1 ' + variable + ' to your order.');

	for(var x=0; x < 1; x++) 
	{
	  var hash_key = variable;
		var temp = window.localStorage.getItem(hash_key);
		temp = temp * 1 + 1;
		window.localStorage.setItem(hash_key, temp);
	}
	location.reload();
} 		

// Function copies data from localStorage to <input> 
$(function()
	{
		orders_input();		
	}
);
</script>