config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get 'comments/index'
  get 'comments/new'
  
  devise_for :users
  resources :posts do
    resources :comments
  end
  resources :places do
    resources :comments
  end

  resources :users
  resources :orders

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Project2</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//maps.google.com/maps/api/js?key=AIzaSyClE56ThQPOKZ9t3lQejb60T3KFt2U5yII"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>    
  </head>

  <body>
    <header>
      <table>
        <tr>
          <%if user_signed_in? %>
            <td>          	  
                <%= link_to 'posts', posts_path %> | <%= link_to 'places', places_path %> | <%= link_to 'adepts', users_path %> | <%= link_to "#{current_user.username}", edit_user_registration_path %> 
                <%if current_user.username == 'admin' %>                
                  | <%= link_to 'orders', orders_path %>
                <% end %>
            </td>
            <td>
              <form action="/orders/new">
                <!-- Order data from LocalStorage is temporary stored here -->
                <input type="hidden" name="orders_btn" id="orders_input" >
                <input type="submit" class="btn-5" value="Coffee order" onclick="orders_input()">
              </form>
            </td>
          <% end %>
        </tr>
      </table>
    </header>
    
    <%= yield %>

  </body>
</html>


<script type="text/javascript">
$(function()
  {
    orders_input();   
  }
);
</script>